### ISSUE TITLE
Odd bug (any ideas?)

### ISSUE THREAD

**Issue by ctsmith95** [VisionistInc/jibe#53]
[2015-07-29 12:28:31.842] [ERROR] console - Possibly unhandled Document not found: The query did not find a document and returned null in:
r.table("rooms").get(null).default(r.error("The query did not find a document and returned null."))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

    at /home/ctsmith/Documents/GitHub/jibe/node_modules/thinky/lib/query.js:161:13
    at tryCatch1 (/home/ctsmith/Documents/GitHub/jibe/node_modules/thinky/node_modules/bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler] (/home/ctsmith/Documents/GitHub/jibe/node_modules/thinky/node_modules/bluebird/js/main/promise.js:627:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/ctsmith/Documents/GitHub/jibe/node_modules/thinky/node_modules/bluebird/js/main/promise.js:641:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/ctsmith/Documents/GitHub/jibe/node_modules/thinky/node_modules/bluebird/js/main/promise.js:800:14)
    at Promise$_settlePromises [as _settlePromises] (/home/ctsmith/Documents/GitHub/jibe/node_modules/thinky/node_modules/bluebird/js/main/promise.js:934:14)
    at Promise$_rejectPromises [as _rejectPromises] (/home/ctsmith/Documents/GitHub/jibe/node_modules/thinky/node_modules/bluebird/js/main/promise.js:927:10)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/ctsmith/Documents/GitHub/jibe/node_modules/thinky/node_modules/bluebird/js/main/async.js:75:12)
    at Async$consumeFunctionBuffer (/home/ctsmith/Documents/GitHub/jibe/node_modules/thinky/node_modules/bluebird/js/main/async.js:38:14)
    at process._tickCallback (node.js:448:13)

**Comment by ctsmith95** [comment]
Just needed to update thinky, I think.

**Comment by markgeraty** [comment]
Haha okay - definitely reopen this if you notice it happening again!
